In [2]:
import numpy as np

In [3]:
n = 10
a = (np.random.rand(n,)*100).astype(int)
k = (np.random.rand(1,1)*100).astype(int).flatten()

In [4]:
print(a,k)

[65 65  6 33 23  6 60  8  0 82] [89]


In [6]:
temp = a.reshape(n,1) + a.reshape(1,n)
temp = temp==k
# print(temp)
if(np.sum(temp)>0):
    print("yesssssss")
else:
    print("Nooooooooo")

In [89]:
print(a.reshape(n,1))
print(a.reshape(1,n))
print(temp)

[[77]
 [51]
 [99]
 [ 2]
 [72]]
[[77 51 99  2 72]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [74]:
index = (a%2).astype(bool)
odd = a[index]
even = a[index==0]

In [ ]:
if(k%2 == 0)