In [1]:
import numpy as np

An important first distinction from lists is that array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array:

In [2]:
a = np.arange(10)

In [3]:
b = a[3:5]
b[0] = 0
print(a)

[0 1 2 0 4 5 6 7 8 9]


Fancy Indexing - 
indexing using integer arrays.
<br>
fancy indexing, unlike slicing, always copies the data into a new array.

In [4]:
tp1 = np.arange(25).reshape(5,5)
print(tp1)
print(tp1[[2,3,1]])    #simply pass a list or ndarray of integers specifying the desired order:

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [ 5  6  7  8  9]]


Passing multiple index arrays does something slightly different; it selects a 1D array of elements corresponding to each tuple of indices

In [23]:
print(tp1[[0,3,2],[1,2,4]]) #chooses(0,1) (3,2) (2,4)

[ 1 17 14]


Slicing
Note : Selecting data from an array by boolean indexing always creates a copy of the data.

In [6]:
print(tp1[:2,2:])   /// first 2 rows and columns after 2nd column  

[[2 3 4]
 [7 8 9]]


In [7]:
print(tp1[:,(2,4)])    ////slicing with fancy indexing

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]
